# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/let4ik/tp_3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/let4ik/tp_3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/let4ik/tp_3/CMakeFiles /Users/let4ik/tp_3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/let4ik/tp_3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pro

# Build rule for target.
pro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pro
.PHONY : pro

# fast build rule for target.
pro/fast:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/build
.PHONY : pro/fast

#=============================================================================
# Target rules for targets named B

# Build rule for target.
B : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B
.PHONY : B

# fast build rule for target.
B/fast:
	$(MAKE) -f B/CMakeFiles/B.dir/build.make B/CMakeFiles/B.dir/build
.PHONY : B/fast

C/main.o: C/main.cpp.o

.PHONY : C/main.o

# target to build an object file
C/main.cpp.o:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/C/main.cpp.o
.PHONY : C/main.cpp.o

C/main.i: C/main.cpp.i

.PHONY : C/main.i

# target to preprocess a source file
C/main.cpp.i:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/C/main.cpp.i
.PHONY : C/main.cpp.i

C/main.s: C/main.cpp.s

.PHONY : C/main.s

# target to generate assembly for a file
C/main.cpp.s:
	$(MAKE) -f CMakeFiles/pro.dir/build.make CMakeFiles/pro.dir/C/main.cpp.s
.PHONY : C/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pro"
	@echo "... B"
	@echo "... C/main.o"
	@echo "... C/main.i"
	@echo "... C/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

